'use client'

import { useState, useEffect } from 'react'

export default function DisclaimerModal() {
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    if (!localStorage.getItem('prelegal_disclaimer_seen')) {
      setVisible(true)
    }
  }, [])

  function dismiss() {
    localStorage.setItem('prelegal_disclaimer_seen', '1')
    setVisible(false)
  }

  if (!visible) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
      <div className="bg-white rounded-2xl shadow-xl max-w-md w-full p-8">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-full flex items-center justify-center shrink-0" style={{ backgroundColor: '#ecad0a20' }}>
            <svg className="w-5 h-5" style={{ color: '#ecad0a' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M12 9v2m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
            </svg>
          </div>
          <h2 className="text-lg font-bold" style={{ color: '#032147' }}>Legal Disclaimer</h2>
        </div>
        <p className="text-sm leading-relaxed text-gray-600">
          Documents generated by PreLegal AI are <strong className="text-gray-800">drafts for review purposes only</strong>.
          They do not constitute legal advice and should be reviewed by a qualified attorney before use,
          execution, or reliance.
        </p>
        <button
          onClick={dismiss}
          className="mt-6 w-full rounded-lg py-2.5 text-sm font-semibold text-white transition-opacity hover:opacity-90"
          style={{ backgroundColor: '#753991' }}
        >
          I understand
        </button>
      </div>
    </div>
  )
}
